language: php

php:
  - "5.5"
  - "5.6"

branches:
  except:
    - development

before_script:
  - cp config/config.yml-dist config/config.yml
  - sed 's/{auth_token}/$AUTH_TOKEN/g' ./config/config.yml | tee ./config/config.yml
  - sed 's/{client_secret}/$CLIENT_SECRET/g' ./config/config.yml | tee ./config/config.yml
  - sed 's/{client_id}/$CLIENT_ID/g' ./config/config.yml | tee ./config/config.yml
  - composer install --prefer-dist -o
  - php vendor/bin/phing install

