language: php

php:
  - "5.4"
  - "5.5"
  - "5.6"

branches:
  except:
    - development

before_script:
  - sed 's/auth_token/'"$API_KEY"'/' config/config.yml-dist > config/config.yml
  - cat config/config.yml
  - composer install --prefer-dist -o
  - php vendor/bin/phing install

